name: Rectify11

on:
  workflow_dispatch:
  push:
  pull_request:
  workflow_run:
    workflows: ["Submodules Sync"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive
        lfs: true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
      with:
        msbuild-architecture: x64

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "8.0"

    - name: Restore NuGet Packages
      run: nuget restore Rectify11Installer.sln

    - name: Build
      run: msbuild Rectify11Installer.sln /p:Configuration=Release /p:platform=x64

    - name: Publish
      run: dotnet publish Rectify11Installer -c Release -p:PublishProfile=FolderProfile -property:SolutionDir=${{ github.workspace }}\
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Upload Rectify11Installer
      uses: actions/upload-artifact@v3
      with:
        name: Rectify11Installer (x64)
        path: D:\a\Installer3\Installer3\Rectify11Installer\bin\Release\net8.0-windows\win-x64\*
        compression-level: 0
